name: "throw-exception"
constructor:
  name: "NewCustomException"
  params:
    - value: "return-value"
not-allowed: true
